version: '3'

volumes:

  fornecedor-db: {}

services:

  fornecedor-db:
    image: sameersbn/postgresql:10-1
    restart: always
    environment:
      DB_NAME: fornecedor-db
      DB_USER: dev
      DB_PASS: dev
      PG_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - fornecedor-db:/var/lib/postgresql
