spring:
  datasource:
    password: dev
    username: dev
    url: jdbc:postgresql://127.0.0.1:5432/loja-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
