
server:
  port: 8086

spring:
  application:
    name: fornecedor-service
  datasource:
    password: dev
    username: dev
    url: jdbc:postgresql://127.0.0.1:5432/fornecedor-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka