
server:
  port: 8086
spring:
  application:
    name: fornecedor-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
logging:
  level:
    root: INFO
  org:
    springframework:
      web: DEBUG
    hibernate: ERROR