server:
  port: 8085
spring:
  application:
    name: loja-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: elias@123
    testWhileIdle: true
    url: jdbc:postgresql://127.0.0.1:5435/loja-microservices
    username: postgres
    validationQuery: SELECT 1
  jpa:
    format-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
logging:
  level:
    root: INFO
  org:
    springframework:
      web: DEBUG
    hibernate: ERROR