
server:  port: 8888
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: microservicos/fornecedor
        git:
          uri: https://github.com/eliasmichalczuk/microservices-spring-cloud
          search-paths: fornecedor, loja
  