
server:  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eliasmichalczuk/microservices-spring-cloud
          search-paths: fornecedor
#        native:
#          search-locations:
  